Allow to set outline visible on app start
lah7/gtk3-classic pull request #65
Opened 2022-02-02 12:07 UTC by luigifab

This allow to set focus visible (`outline`) on application start by setting GTK_FOCUS_VISIBLE=1` env variable.

2022-02-02 18:21 UTC, lah7 commented
Heads up! The force push was to update the checksum ❌ → ✅ , and drop `.SRCINFO` (0ada921f9311bb9da49ab0a8c8a1aff6522f0578, it's not needed) so I can test your changes.

2022-02-02 18:30 UTC, lah7 commented
I had a look, but I'm not seeing a difference in some MATE programs. Does it depend on the theme to show the outline?

Please could you show me a screenshot with and without `GTK_FOCUS_VISIBLE` set? 📸

2022-02-02 18:38 UTC, luigifab commented
Yes, you have screenshots in #59.
It depends on the theme used.

You can try `mate-notification-properties`, there is auto focus on the first select, and `mate-keyboard-properties`, there is auto focus on the close button.

2022-02-02 20:02 UTC, lah7 requested changes
I tried a few MATE themes and checked on an **unpatched** Ubuntu MATE 21.04 (Ambiant-MATE theme) and found the focus outline already works if that control has initial focus:

* `mate-notification-properties` (first combo box) 
    ![Screenshot_20220202_195120](https://user-images.githubusercontent.com/13032135/152226574-3aaa2c37-1111-4b29-b13c-f376ae8b578d.png)
* `mate-keyboard-properties` (close button)
    ![Screenshot_20220202_195056](https://user-images.githubusercontent.com/13032135/152226526-c237e323-4f43-45e4-bad8-453ae3be5ff6.png)
* Caja: Pressing tab & arrow keys for navigation shows the focus
![Screenshot_20220202_195206](https://user-images.githubusercontent.com/13032135/152226719-67ff9ffa-75e8-4c6f-ba06-afda5d63a52f.png)

The behaviour doesn't seem broken. I'm not sure this patch will do anything for the majority of applications and users.

I appreciate you might be trying to restore the original GTK+2 focus look (#59), maybe adding optional CSS in `~/.config/gtk-3.0/gtk.css` to override focused buttons might be the way to go? It'll probably vary by theme [like it does for the alternating rows](https://github.com/lah7/gtk3-classic/wiki/Treeview:-Alternating-Colours-CSS).

2022-02-03 08:46 UTC, luigifab commented
Interesting... but I checked how Ambiant-MATE theme do it (because I'm surprised), but it use `border-color` and not `outline`.

If you add in `~/.config/gtk-3.0/gtk.css`:
```css
* { outline:1px solid red; outline-offset:10px; }
```

On start we have:
![image](https://user-images.githubusercontent.com/31816829/152309461-6e3463d9-f4ac-4ec1-b01f-c5097842c0ac.png)

After pressing tab:
![image](https://user-images.githubusercontent.com/31816829/152309503-1b14bd9a-b914-4ad2-99ba-997b751c04fd.png)

2022-02-03 12:16 UTC, lah7 commented
I'm going to close this as the proposed change doesn't appear to work as intended. Please see https://github.com/lah7/gtk3-classic/issues/59#issuecomment-1028930503 for further comment.

2022-02-03 12:16 UTC, closed without merging